version: "3.7"
services:
  database:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=flow_docs_user
      - POSTGRES_PASSWORD=flow_docs_pass
      - POSTGRES_DB=flow_docs_db
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  cache:
    image: 'redis:alpine'
    command: redis-server --requirepass flow_docs
    volumes:
      - .redis-data:/data
    ports:
      - '6379:6379'