version: "3.7"
services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass flow_docs
    expose:
      - '6379'
    volumes:
      - ./.cache/redis:/data
    ports:
      - '6379:6379'
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
